
-- ------------- ANALYSIS WORLD TOTAL POPULATION -----------------------------------

-- DATA SOURCE 
-- https://data360.worldbank.org/en/indicator/WB_HNP_SP_POP_TOTL?view=datatable

CREATE DATABASE world_population;

-- IMPORT DATA WORLD POPULATION TABLE NAME POPULATION --

-- OVERVIEW OF TABLE
SELECT *
FROM population;

-- CHECK THE COLUMN NAMES AND DATA TYPES
DESCRIBE population;

-- THE NUMBER OF COUNTRIES
SELECT COUNT(DISTINCT REF_AREA_NAME)
FROM population;

-- 1960 AND 2023 WORLD TOTAL POPULATION
SELECT FORMAT(SUM(`1960`),0) AS WT_POPULATION_1960, FORMAT(SUM(`2023`),0) AS WT_POPULATION_2023
FROM population
WHERE SEX_ID = 'ALL_T';  

-- TO EASILY GET ALL THE COLUMNS NO NEED TO TYPE EACH COLUMN IN SELECT STATEMENT (copy - paste the result)
SELECT CONCAT('`',column_name,'`',',',' ')
FROM information_schema.columns
WHERE table_name = 'population';

-- GET THE TOTAL POPPULATION FROM 1960 TO 2023 FOR EACH COUNTRY 
SELECT REF_AREA_NAME, `1960`, `1961`, `1962`, `1963`, `1964`, `1965`, `1966`, `1967`, `1968`, `1969`, `1970`, `1971`, `1972`,
	   `1973`, `1974`, `1975`, `1976`, `1977`, `1978`, `1979`, `1980`, `1981`, `1982`, `1983`, `1984`, `1985`, `1986`, `1987`, 
	   `1988`, `1989`, `1990`, `1991`, `1992`, `1993`, `1994`, `1995`, `1996`, `1997`, `1998`, `1999`, `2000`, `2001`, `2002`, 
	   `2003`, `2004`, `2005`, `2006`, `2007`, `2008`, `2009`, `2010`, `2011`, `2012`, `2013`, `2014`, `2015`, `2016`, `2017`, 
		`2018`, `2019`, `2020`, `2021`, `2022`, `2023`
FROM population
WHERE SEX_ID = 'ALL_T' AND AGE_NAME = 'All age ranges or no breakdown by age'
ORDER BY 1;

-- ---------------------------------------------------------------------------

-- MAX, MIN, AVG POPULATION 2023 AND 1960 
SELECT "2023" `Year`, FORMAT(MAX(`2023`),0) `Max`, FORMAT(MIN(`2023`),0) `Min`, ROUND(AVG(`2023`),2) `Avg` 
FROM population WHERE SEX_ID = 'ALL_T'
UNION
SELECT "1960" `Year`, FORMAT(MAX(`1960`),0) `Max`, FORMAT(MIN(`1960`),0) `Min`, ROUND(AVG(`1960`),2) `Avg` 
FROM population WHERE SEX_ID = 'ALL_T' ;

-- ---------------------------------------------------------------------------
-- WORLD TOTAL POPULATION RURAL
SELECT FORMAT(SUM(`2023`),0) AS TOTAL_POPULATION_RUR 
FROM population
WHERE SEX_ID = 'RUR_T'; 

 -- WORLD TOTAL POPULATION URBAN
SELECT FORMAT(SUM(`2023`),0) AS WORLD_TOTAL_POPULATION_URB 
FROM population
WHERE SEX_ID = 'URB_T'; 

-- WORLD TOTAL POPULATION MALE AND FEMALE 

SELECT FORMAT(SUM(`2023`),0) AS WORLD_TOTAL_FEMALE, 
(SELECT FORMAT(SUM(`2023`),0) AS WORLD_TOTAL_MALE FROM population WHERE SEX_ID = 'M_T') AS WORLD_TOTAL_MALE
FROM population
WHERE SEX_ID = 'F_T'; 
-- --------------------------------------------------------------------------

--  2023 WORLD TOTAL POPULATION AGE UNDER 15, AGE 15 TO 65, AGE OVER 65

SELECT 'AGE_UNDER_15'  `CATEGORY`, FORMAT(SUM(`2023`),0) AS TOTAL_POPULATION
FROM population
WHERE SEX_ID = '_T' AND AGE_NAME = 'under 15 years old'
UNION 
SELECT 'AGE_15_To_64'  `CATEGORY`, FORMAT(SUM(`2023`),0) AS TOTAL_POPULATION
FROM population
WHERE SEX_ID = '_T' AND AGE_NAME = '15 to 64 years old'
UNION 
SELECT 'AGE_OVER_65'  `CATEGORY`, FORMAT(SUM(`2023`),0) AS TOTAL_POPULATION
FROM population
WHERE SEX_ID = '_T' AND AGE_NAME = '65 years old and over';

-- ----------------------------------------------------------------------------------


--  GROWTH RATE FROM 2022 TO 2023 WORLD TOTAL POPULATION
SELECT REF_AREA_NAME, `2022`,`2023`,
((`2023` - `2022`) / `2022`) * 100 AS GROWTH_RATE
FROM population
WHERE SEX_ID ='ALL_T'
ORDER BY GROWTH_RATE;

--  GROWTH RATE ALL COUNTRY FROM 1960 TO 2023 WORLD TOTAL POPULATION
SELECT REF_AREA_NAME AS COUNTRY, `1960`,`2023`,
((`2023` - `1960`) / `1960`) * 100 AS GROWTH_RATE
FROM population
WHERE SEX_ID ='ALL_T'
ORDER BY REF_AREA_NAME;

-- TOP 5 COUNTRIES WITH THE FASTEST GROWTH RATE FROM 1960 TO 2023 WORLD TOTAL POPULATION
SELECT REF_AREA_NAME AS COUNTRY, `1960`,`2023`,
((`2023` - `1960`) / `1960`) * 100 AS GROWTH_RATE
FROM population
WHERE SEX_ID ='ALL_T'
ORDER BY GROWTH_RATE DESC
LIMIT 5;

-- TOP 5 COUNTRIES WITH THE SLOWEST GROWTH RATE FROM 1960 TO 2023 WORLD TOTAL POPULATION
SELECT REF_AREA_NAME AS COUNTRY, `1960`,`2023`,
((`2023` - `1960`) / `1960`) * 100 AS GROWTH_RATE
FROM population
WHERE SEX_ID ='ALL_T'
ORDER BY GROWTH_RATE ASC
LIMIT 5;

-- --------------------------------------------------------------------------------------------

-- TOP 12 COUNTRY WITH THE HIGHEST POPULATION 2023
SELECT REF_AREA_NAME AS COUNTRY, FORMAT(`2023`,0) AS HIGHEST_POPULATION
FROM population
WHERE SEX_ID = 'ALL_T' 
ORDER BY `2023` DESC
LIMIT 12;

-- TOP 12 COUNTRY WITH THE LOWEST POPULATION 2023
SELECT REF_AREA_NAME AS COUNTRY, FORMAT(`2023`,0) LOWEST_POPULATION
FROM population
WHERE SEX_ID = 'ALL_T' 
ORDER BY `2023` ASC
LIMIT 12;


-- ---------------------------------------------------------------------------------
-- COUNTRIES THAT HAS MORE FEMALE POPULATION 2023 USIMG CTE AND JOIN
 WITH CTE_1F AS    
	(	SELECT REF_AREA_NAME AS COUNTRY, FORMAT(`2023`,0) AS  TOTAL_FEMALE
		FROM population
		WHERE SEX_ID = 'F_T' 
	),
CTE_2F AS
	(	SELECT REF_AREA_NAME AS COUNTRY, FORMAT(`2023`,0) AS  TOTAL_MALE
		FROM population 
		WHERE SEX_ID = 'M_T' 
	)	
    
 SELECT   A.COUNTRY, A.TOTAL_FEMALE, B.TOTAL_MALE
 FROM CTE_1F A
 JOIN CTE_2F B
 WHERE A.TOTAL_FEMALE > B.TOTAL_MALE
 AND A.COUNTRY = B.COUNTRY
 ORDER BY A.COUNTRY;
-- --------------------------------------------------
 -- COUNTRIES THAT HAS MORE MALE POPULATION 2023
 
 WITH CTE_1M AS    
	(	SELECT REF_AREA_NAME AS COUNTRY, FORMAT(`2023`,0) AS  TOTAL_MALE
		FROM population
		WHERE SEX_ID = 'M_T' 
	),
CTE_2M AS
	(	SELECT REF_AREA_NAME AS COUNTRY, FORMAT(`2023`,0) AS  TOTAL_FEMALE
		FROM population
		WHERE SEX_ID = 'F_T' 
	)	
    
 SELECT   A.COUNTRY, A.TOTAL_MALE, B.TOTAL_FEMALE
 FROM CTE_1M A, CTE_2M B
 WHERE  A.TOTAL_MALE > B.TOTAL_FEMALE
 AND A.COUNTRY = B.COUNTRY
 ORDER BY A.COUNTRY;
 
 -- -------------------------------------------------------------------------------------
 
 -- POPULATION CATEGORY LARGE, MEDIUM, SMALL 
-- USING SUBQUERY AT THE END  + (CASE,ROW_NUMBER,PARTITION BY) 

SELECT REF_AREA_NAME, `2023`, POPULATION_CATEGORY,
ROW_NUMBER() OVER (partition by POPULATION_CATEGORY) AS RANK_CATEGORY
FROM
	(SELECT REF_AREA_NAME, `2023`,
		CASE 
			WHEN `2023` > 500000000 THEN 'LARGE POPULATION'
			WHEN `2023` BETWEEN 100000000 AND 500000000 THEN 'MEDIUM POPULATION'
			ELSE 'SMALL POPULATION'
		END AS POPULATION_CATEGORY
	FROM population
	WHERE SEX_ID = 'ALL_T') SUB;
    
-- --------------------------------------------------------------------------------
    
-- POPULATION BY CATEGORY LARGE, MEDIUM, SMALL 
-- USING CTE + (CASE,ROW_NUMBER,PARTITION BY) 
    
    WITH CTE_CATEGORY AS 
(
SELECT REF_AREA_NAME, `2023`,
	CASE 
		WHEN `2023` > 500000000 THEN 'LARGE POPULATION'
		WHEN `2023` BETWEEN 100000000 AND 500000000 THEN 'MEDIUM POPULATION'
		ELSE 'SMALL POPULATION'
	END AS POPULATION_CATEGORY
FROM population
WHERE SEX_ID = 'ALL_T'
)
SELECT REF_AREA_NAME, `2023`, POPULATION_CATEGORY,
ROW_NUMBER() OVER (partition by POPULATION_CATEGORY) AS RANK_CATEGORY
FROM CTE_CATEGORY;

-- --------------------------------------------------------------------------------
-- TOP 8 COUNTRY WITH THE HIGHEST PERCENTAGE OF AGE OVER 65  POPULATION 2023

WITH CTE_percentage AS
(
SELECT REF_AREA_NAME AS Country,  `2023`, (`2023` / (SELECT SUM(`2023`) FROM population WHERE SEX_ID = '_T' AND AGE_NAME = '65 years old and over')) * 100 AS Percentage_of_total
FROM population
WHERE SEX_ID = '_T' AND AGE_NAME = '65 years old and over'
)
SELECT Country, `2023`, Percentage_of_total
FROM CTE_percentage
ORDER BY Percentage_of_total DESC
LIMIT 8;

-- TOP 8 COUNTRY WITH THE LOWEST PERCENTAGE OF AGE OVER 65  POPULATION 2023
WITH CTE_percentage AS
(
SELECT REF_AREA_NAME AS Country,  `2023`, (`2023` / (SELECT SUM(`2023`) FROM population WHERE SEX_ID = '_T' AND AGE_NAME = '65 years old and over')) * 100 AS Percentage_of_total
FROM population
WHERE SEX_ID = '_T' AND AGE_NAME = '65 years old and over'
)

SELECT Country, `2023`, Percentage_of_total
FROM CTE_percentage
ORDER BY Percentage_of_total ASC
LIMIT 8;

-- TOP 8 COUNTRY WITH THE HIGHEST PERCENTAGE OF AGE 65+  POPULATION 1960

SELECT REF_AREA_NAME AS Country,  `1960`, 
(`1960` / (SELECT SUM(`1960`) FROM population WHERE SEX_ID = '_T' AND AGE_NAME = '65 years old and over')) * 100 AS Percentage_of_total
FROM population
WHERE SEX_ID = '_T' AND AGE_NAME = '65 years old and over'
ORDER BY Percentage_of_total DESC
LIMIT 8;

-- TOP 8 COUNTRY WITH THE lowest PERCENTAGE OF AGE 65+  POPULATION 1960
SELECT REF_AREA_NAME AS Country,  `1960`, 
(`1960` / (SELECT SUM(`1960`) FROM population WHERE SEX_ID = '_T' AND AGE_NAME = '65 years old and over')) * 100 AS Percentage_of_total
FROM population
WHERE SEX_ID = '_T' AND AGE_NAME = '65 years old and over'
ORDER BY Percentage_of_total ASC
LIMIT 8;

-- ------------------------------------------------------------------------------------------------

-- TOP 5 COUNTRY WIYH THE HIGHEST FEMALE POPULATION
SELECT REF_AREA_NAME AS COUNTRY, FORMAT(`2023`,0) AS  TOTAL_FEMALE,
ROW_NUMBER() OVER (ORDER BY `2023` DESC) AS RANK_F_COUNTRY
FROM population
WHERE SEX_ID = 'F_T' 
LIMIT 5;

-- TOP 5 COUNTRY WIYH THE HIGHEST FEMALE POPULATION 1960
SELECT REF_AREA_NAME AS COUNTRY, FORMAT(`1960`,0) AS  TOTAL_FEMALE,
ROW_NUMBER() OVER (ORDER BY `1960` DESC) AS RANK_F_COUNTRY
FROM population
WHERE SEX_ID = 'F_T' 
LIMIT 5;


-- TOP 5 COUNTRY WIYH THE HIGHEST MALE POPULATION 2023
SELECT REF_AREA_NAME AS COUNTRY, FORMAT(`2023`,0) AS  TOTAL_MALE,
ROW_NUMBER() OVER (ORDER BY `2023` DESC) AS RANK_F_COUNTRY
FROM population 
WHERE SEX_ID = 'M_T' 
LIMIT 5;

-- TOP 5 COUNTRY WIYH THE HIGHEST MALE POPULATION 1960
SELECT REF_AREA_NAME AS COUNTRY, FORMAT(`1960`,0) AS  TOTAL_MALE,
ROW_NUMBER() OVER (ORDER BY `1960` DESC) AS RANK_F_COUNTRY
FROM population
WHERE SEX_ID = 'M_T' 
LIMIT 5;

-- DIFFERENT FUNCTION EXAMPLE USING ROW_NUMBER, RANK, AND DENSE_RANK
SELECT REF_AREA_NAME AS COUNTRY, FORMAT(`2023`,0) AS  TOTAL_FEMALE,
ROW_NUMBER() OVER (ORDER BY `2023` DESC) AS ROW_NUM,  -- e.g. 12345
RANK() OVER (ORDER BY `2023` DESC) AS RANK_NUM,       -- e.g. 12335 
DENSE_RANK() OVER (ORDER BY `2023` DESC) AS DENSE_NUM -- e.g. 12334
FROM population
WHERE SEX_ID = 'F_T'; 

-- -------------------------------------------------------------------------------

-- STORED PROCEDURE FOR EASILY GETTING POPULATION 2023 BY CATEGORY
/*
DELIMITER $$
CREATE PROCEDURE GETPOPULATION2023_BY_CATEGORY(IN SEX_ID_PARAM VARCHAR(250),IN AGE_ID_PARAM VARCHAR(250))
BEGIN
	SELECT REF_AREA_NAME, `2023`
	FROM population
	WHERE SEX_ID = SEX_ID_PARAM AND AGE_ID = AGE_ID_PARAM
    ORDER BY 2 DESC;
END $$
DELIMITER ;

CALL GETPOPULATION2023_BY_CATEGORY('_T', 'Y_GE65');

-- DROP PROCEDURE GETPOPULATION2023_BY_CATEGORY;
*/
-- -------------THANK YOU SO MUCH!-----------------------------------------------


-- OVERVIEW OF TABLE
-- CHECK THE COLUMN NAMES AND DATA TYPES
-- THE NUMBER OF COUNTRIES
-- 1960 AND 2023 WORLD TOTAL POPULATION
-- GET THE TOTAL POPPULATION FROM 1960 TO 2023 FOR EACH COUNTRY 
-- MAX, MIN, AVG POPULATION 2023 AND 1960 
-- WORLD TOTAL POPULATION RURAL
-- WORLD TOTAL POPULATION URBAN
-- WORLD TOTAL POPULATION MALE AND FEMALE 
--  2023 WORLD TOTAL POPULATION AGE UNDER 15, AGE 15 TO 65, AGE OVER 65
--  GROWTH RATE FROM 2022 TO 2023 WORLD TOTAL POPULATION
--  GROWTH RATE ALL COUNTRY FROM 1960 TO 2023 WORLD TOTAL POPULATION
-- TOP 5 COUNTRIES WITH THE FASTEST GROWTH RATE FROM 1960 TO 2023 WORLD TOTAL POPULATION
-- TOP 5 COUNTRIES WITH THE SLOWEST GROWTH RATE FROM 1960 TO 2023 WORLD TOTAL POPULATION
-- TOP 12 COUNTRY WITH THE HIGHEST POPULATION 2023
-- TOP 12 COUNTRY WITH THE LOWEST POPULATION 2023
-- COUNTRIES THAT HAS MORE FEMALE POPULATION 2023 USIMG CTE AND JOIN
-- COUNTRIES THAT HAS MORE MALE POPULATION 2023
-- POPULATION CATEGORY LARGE, MEDIUM, SMALL - USING SUBQUERY AT THE END  + (CASE,ROW_NUMBER,PARTITION BY) 
-- TOP 8 COUNTRY WITH THE HIGHEST PERCENTAGE OF AGE OVER 65  POPULATION 2023
-- TOP 8 COUNTRY WITH THE LOWEST PERCENTAGE OF AGE OVER 65  POPULATION 2023
-- TOP 8 COUNTRY WITH THE HIGHEST PERCENTAGE OF AGE 65+  POPULATION 1960
-- TOP 8 COUNTRY WITH THE lowest PERCENTAGE OF AGE 65+  POPULATION 1960
-- TOP 5 COUNTRY WIYH THE HIGHEST FEMALE POPULATION
-- TOP 5 COUNTRY WIYH THE HIGHEST FEMALE POPULATION 1960
-- TOP 5 COUNTRY WIYH THE HIGHEST MALE POPULATION 2023
-- TOP 5 COUNTRY WIYH THE HIGHEST MALE POPULATION 1960
-- DIFFERENT FUNCTION EXAMPLE USING ROW_NUMBER, RANK, AND DENSE_RANK
-- STORED PROCEDURE FOR EASILY GETTING POPULATION 2023 BY CATEGORY

